nxp-s32g2xx: README: update load addresses for kernel and fdt to adapt to larger kernel images
Issue: LINCD-5236 LINCD-5231

If kernel image is larger than normal, like more kernel configs enbaled
for debug or test, then the default load addresses of kernel and fdt may
not suitable and errors may comeout like:

	ERROR: Did not find a cmdline Flattened Device Tree
or
	Trying to unpack rootfs image as initramfs...
	rootfs image is not initramfs (invalid magic at start of compressed archive); looks like an initrd
	BUG: Bad page state in process swapper/0  pfn:840d9
	page:(____ptrval____) refcount:0 mapcount:-128 mapping:0000000000000000 index:0x1 pfn:0x840d9
	flags: 0x0()
	raw: 0000000000000000 dead000000000100 dead000000000122 0000000000000000
	raw: 0000000000000001 0000000000000000 00000000ffffff7f 0000000000000000
	page dumped because: nonzero mapcount
	Modules linked in:
	CPU: 0 PID: 1 Comm: swapper/0 Not tainted 5.10.30-yocto-standard #1

and so on, that's because the memory layout has been changed due to
the larger kernel image, so change the default values of load addresses
to adapt to larger kernel images.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>