sja1105: set base_libdir to be noarch version
Issue: LINUXEXEC-12308

This patch is to replace base_libdir with nonarch_base_libdir,
otherwise, there will be error when do_package:

ERROR: sja1105-1.0-r0 do_package: QA Issue: sja1105: Files/directories were installed but not shipped in any package:
  /lib/firmware
  /lib/firmware/sja1105p_1-1_cfg.bin

The reason is that, base_libdir is /lib64 indeed, and nonarch_base_libdir
is /lib, and the firmware will be put in /lib dir, so correct it.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>