Revert "nxp-s32g2xx: add ipc-shm to PNWHITELIST"
do_package error:
ERROR: ipc-shm-1.0-r0 do_package: QA Issue: ipc-shm: Files/directories were installed but not shipped in any package:
  /lib/modules/5.10.35-yocto-standard/kernel/drivers/ipc-shm/ipc-shm-sample.ko
  /lib/modules/5.10.35-yocto-standard/kernel/drivers/ipc-shm/ipc-shm-uio.ko
  /lib/modules/5.10.35-yocto-standard/kernel/drivers/ipc-shm/ipc-shm-dev.ko

So revert it temporarily.

This reverts commit 6cb759ac3649d73e89aedb3d710da3af97b754a4.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>