nxp-s32g2xx: sja1105: update bb file to fix dnf invoke error
Issue: LINUXEXEC-13319

This patch is to fix the following error:

    ERROR: wrlinux-image-std-1.0-r5 do_rootfs: Could not invoke dnf. Command
    ...
    Error:
     Problem: conflicting requests
      - nothing provides kernel-module-sja1105pqrs-5.10.30-yocto-standard needed by sja1105-1.0-r0.nxp_s32g2xx

The cause is that, in the default bb file, even PROVIDES and RPROVIDES_${PN}
set, the kernel-module-sja1105pqrs-xxx.rpm will not be built, so update
bb file to fix the error. Moreover, delete the auto load set for sja1105pqrs
kernel module to prevent switching off related sja1105 ports which enabled by
u-boot command "sja probe 5:0 && sja speed -,-,-,1G,1G 5:0".

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>