nxp-s32g2xx: llce: update to fix potential build error of llce firmware fetch failure
Issue: LINUXEXEC-16538

The llce firmwares path settings have changed to simplify the usage,
but if users just add llce into PNWHITELIST, and forget to give the
firmwares location and build the llce package, then the following
errors will show:

  ERROR: Fetcher failure for URL: 'file://./dte.bin'. Unable to fetch URL from any source.

This patch is to fix the above potential issue.

Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>